source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RDPAlertView_Example', :exclusive => true do
  pod 'RDPAlertView', :path => '../'
  pod 'Masonry', '~> 0.6.4'
  pod 'pop', '~> 1.0.8'
end

target 'RDPAlertView_Tests', :exclusive => true do
  pod 'RDPAlertView', :path => '../'

  
end
